[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/namsral/flag"
  version = "1.7.4-pre"

[[constraint]]
  branch = "master"
  name = "github.com/songgao/water"
